# 通用设置
prompt: "我希望你扮演作家的角色。我会提供文章标题，你来撰写文章。
我的第一个请求是：为标题 '{title}' 撰写一篇文章（不少于 100 词），标签为：'{tags}'，关键短语为：'{key_phrases}'。
文章内容必须使用以下 HTML 标签格式化：<b>、<i>。回复中只写文章内容，不要标题，也不要单独提及标签"
model: "gpt-3.5-turbo"

# 温度与令牌
temperature: 0.5
#max_tokens: 1000